### ISSUE TITLE
Setting up the ridgeback yumi IP and time sync

### ISSUE THREAD

**Issue by diogoalmeida** [kth-ros-pkg/ridgeback_yumi#3]
Hi,

Currently, there are two setup steps that must be repeated everytime the ridgeback yumi restarts, and I believe both could be avoided with some extra configuration on the workstation. This serves both as an issue and as a reference for anyone trying to use the robot.

Right now you need to manually configure your ip
``$ sudo ifconfig <interface> 192.168.125.50``, where <interface> is eno1 for the current workstation, but depends on the network interface that's connected to the robot.

To make sure you don't have issues when communicating with the robot, you need to synchronize clocks,
``$ sudo ntpdate cpr-ridgeback``. 

I understand that these solutions are present in the wiki, but it would be nicer to not even have to care about it once the workstation is ready to use.
Is it possible to configure the workstation such that a new user doesn't have to do this? 

Thanks,
Diogo

**Comment by diogoalmeida** [comment]
PS: @YoshuaNava  if you point me on the right direction, I can do this and spare you the effort.

**Comment by diogoalmeida** [comment]
@igmitsio

**Comment by diogoalmeida** [comment]
@AliGhadirzadeh

**Comment by YoshuaNava** [comment]
Hey @diogoalmeida, @igmitsio, @AliGhadirzadeh 

I divided this reply in two sections:

**IP address setup**
In the past we were using WiFi, but now that we're all connecting to ridgeback_yumi over wire, this could be made permanent. If everyone agrees we could set the IP permanently on port **eno1** of the desktop PC.

Manual configuration of the IP address can be automated by setting it statically, In order to do this, open the file `etc/network/interfaces` and add the following lines at the end:

```
auto eno1
iface eno1 inet static
address 192.168.125.50
netmask 255.255.255.0
```

Then, restart the interface by running:
```
sudo ifdown eno1 && sudo ifup eno1
```

PS: I also added this info to the [YuMi wiki](https://github.com/kth-ros-pkg/yumi/wiki/Network-setup), and now referenced it on the [ridgeback_yumi wiki](https://github.com/kth-ros-pkg/ridgeback_yumi/wiki/Network-setup). The WiFi network would still be available to connect to the ridgeback, NUC/Jetson boards and YuMi (over ABB RobotStudio).

**Time synchronization**

With respect to this I have already set up `chrony` to synchronize the clocks, but it seems that it's not doing it fast enough.

Something we could do is to set up the main computer as the time server, and configure ridgeback to grab the time from it using ntp. In order to do that, I would follow [this guide](https://help.ubuntu.com/lts/serverguide/NTP.html), section Serving NTP, and add `server 192.168.125.50` to `/etc/ntp.conf`

If you try this out please let me know how it goes.


Thanks for the feedback. If you have any other questions you can contact me and I'd gladly help!

**Comment by diogoalmeida** [comment]
I've changed the file in ``/etc/network/interfaces`` as you suggested, but if I restart the router on ridgeback we still get ``192.168.1.100`` as the IP. If I bring down the interface and then back up, then it gets the right address.

**Comment by YoshuaNava** [comment]
@diogoalmeida 

I forgot to mention that you need to restart the interface when you set up a new config in `/etc/network/interfaces`. I'll edit the message on top of this one to fix that.

**Comment by diogoalmeida** [comment]
My point is that I had to run ``sudo ifdown eno1 && sudo ifup eno1`` everytime I restarted the router on ridgeback, which kinda defeats the purpose of not having the user be bothered with it :)

**Comment by YoshuaNava** [comment]
Hey @diogoalmeida,
Once you have edited the interfaces file and restarted the interface once, it should take the static IP, and the network daemon should be setting the IP directly every time you power on the PC. As we are setting the IP statically, interface *eno1* on the desktop PC will have the proper IP regardless of the router config.

Most of the devices we use request a dynamic IP address (via DHCP, a protocol for that purpose) to another node (e.g. a router) when they connect to a common network. But, when a device is assigned a static IP address, the device doesn't request an IP to other machines in the network, so the address does not change.

There is no need to restart the router on ridgeback. After restarting the interface and the ridgeback router, did you see that the IP changed?

**Comment by diogoalmeida** [comment]
Yes, the IP changes. If I restart the router on the ridgeback (or if I power down the ridgeback and turn it back on), the IP resets to something else than what I configured.

**Comment by diogoalmeida** [comment]
After restarting the workstation, the IP is set correctly, and we correctly set up a timeserver on the workstation to solve the time sync issues. Thanks for the help @YoshuaNava!
